### ISSUE TITLE
Question about `ddt`

### ISSUE THREAD

**Issue by tuanpham96** [chenxinfeng4/ArControl-covert2-nwb#1]
Why was `ddt` of 0.1 ms necessary to be added? 

https://github.com/chenxinfeng4/ArControl-convert2-nwb/blob/6e93e747f9fdf46293f45877b4e706030487c2db/arcontrol2nwb/converter_cli.py#L177-L180

**Comment by chenxinfeng4** [comment]
**Conversion from discrete events to continous series need some ticks.** ArControl is 1ms accurancy. The ddt is any time < 1ms, which is just to tell **this is the rising/downing edge of signal event** without affect the original start-time and end-time.
